- name: precedence of variables
  hosts: frontend
  vars:
   - name1: playlevel
  # vars_files:
  # - details.yaml
  # vars_prompt:
  # - name: name1
  #   prompt: enter your name
  #   private: no
  tasks:
  - name: printing variables from precedence
    # vars:
    #  - name1: tasklevel
    ansible.builtin.debug:
     msg: "my name is {{ name1 }}"   
#01-args
#02-task-level
#03-var_file
#04-vars_prompt