- name: Functions or filters in ansible
  hosts: localhost
  connection: local
  vars:
   technologies: devops,linux,shell,aws
   address:
    city: hyd
    street: lakdikapul
    pincode: 539379 
  tasks:
  - name: creating default variable
    ansible.builtin.debug:
     msg: "{{name | default('ram')  }}"
  - name: convert string to list
    ansible.builtin.debug:
     msg: "{{technologies | split(',')}}"  
  - name: convert map to list
    ansible.builtin.debug:
     msg: "{{address | dict2items}}"    