- name: error handling
  hosts: localhost
  connection: local
  tasks:
  - name: checking user 
    ansible.builtin.command: iid roboshop
    register: output
    ignore_errors: true
  - name: printing the output
    ansible.builtin.debug:
     msg: "{{output}}"  

